config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/add_friend/:friend_id', to: 'friendships#create', as: :send_request
  put '/accept_friend/:sender_id', to: 'friendships#accept', as: :accept_request
  delete '/reject_friend/:sender_id', to: 'friendships#reject', as: :reject_request
  get '/received_requests', to: 'users#show', as: :received_requests
  get '/users', to: "users#index", as: :users
  get '/add_comment/:post_id', to: 'comments#new', as: :show_comment
  post '/add_comment/:post_id', to: 'comments#create', as: :create_comment
  get '/add_like/:post_id', to: 'likes#create', as: :like
  delete '/delete_like/:post_id', to: 'likes#destroy', as: :unlike
  resources :posts
  devise_for :users,
  :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' },
  :skip => [:registrations, :sessions]
  root to: "posts#index"
  
  devise_scope :user do
    get "/profile", to: "users/registrations#show"
    get "/signup", to: "users/registrations#new", as: :signup
    post "user/sign_up", to: "users/registrations#create", as: :user_registration
    post "/signin", to: "users/sessions#create", as: :signin
    get "/edit_user", to: "users/registrations#edit", as: :user_edit
    patch "/edit_user", to: "users/registrations#update" 
    delete "/signout", to: "users/sessions#destroy", as: :signout
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts
  has_many :likes
  has_many :comments
  has_many :sent_requests, foreign_key: 'sender_id', class_name: 'Friendship'
  has_many :received_requests, foreign_key: 'receiver_id', class_name: 'Friendship'
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable,
         :omniauthable, omniauth_providers: [:facebook]
  validates :first_name, presence: true, length: { maximum: 25 }
  validates :last_name, presence: true, length: { maximum: 25 }
  validates :location, length: { maximum: 40 }
  validates :bio, length: { maximum: 150 }
  validates_inclusion_of :gender, in: %w[Male Female], allow_nil: true
  validates_inclusion_of :status, in: ['Single', 'Married', 'In a relationship'], allow_nil: true

  def friends
    sent_requests.map { |friendship| friendship.sender_id if friendship.status == 'accepted' }.compact
  end

  def self.all_friends(user_id)
    User.where('id != ?', user_id)
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if (data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info'])
        user.email = data['emai'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.name.split(' ')[0]
      user.last_name = auth.info.name.split(' ')[1]
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to root_path
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :authorize, only: [:show]

  def new
    super
  end

  def create
    super
  end

  def edit
    super
    @user = current_user
  end

  def show
    @user = current_user
    @posts = Post.where(user_id: current_user.id)
  end

  def update
    if @user.update(user_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:email, :password, :password_confirmation, :first_name, :last_name)
    end
  end

  def user_params
    params[:user].permit(:first_name, :last_name, :gender, :link_image,
                         :location, :date_of_birth, :status, :bio)
  end

  def user_signed_in?
    super
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  include Devise::Controllers::Rememberable
  def create
    @user = User.find_by(email: params[:session][:email])
    if @user&.valid_password?(params[:session][:password])
      sign_in(@user)
      remember_me current_user if params[:session][:remember_me] == '1'
      redirect_to root_path
    else
      flash.now[:notice] = 'Wrong email or password for login'
      @user = User.new
      render 'devise/registrations/new'
    end
  end

  def destroy
    sign_out(current_user)
    redirect_to root_path
  end

  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:session) do |u|
      u.permit(:email, :password, :remember_me)
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.all_friends(current_user.id)
  end

  def show
    @requests = Friendship.where('receiver_id = ? and status = ?', current_user.id, 'pending')
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/index.html.erb
<div class="container">
  <p id="danger" class="center center-align green-text"><%= notice %></p>
  <% @users.each do |user|%>
    <div class="card user-item">
      <div class="grouped-items">
        <%= gravatar_for user, size: 50 %>
        <h4><%= user.first_name %> <%= user.last_name %></h4>
      </div>
      <% if request_sent?(user.id) == 'pending' %>
        <a class="waves-effect waves-light btn disabled"><i class="material-icons left">autorenew</i>Pending</a>
      <% elsif request_sent?(user.id) == 'rejected' %>
        <%= link_to send_request_path(user.id), class:'darken-4 btn-flat follow-btn' do %>
          <i class="material-icons left">group_add</i>Add Friend
        <% end %>
      <% else %>
        <%= nil %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <p id="danger" class="center center-align green-text"><%= notice %></p>
  <% if @requests.empty? %>
    <h3 class="center center-align">No Pending Requests</h3>
  <% end %>
  <% @requests.each do |request|%>
    <div class="card pending-item">
      <div class="grouped-items">
        <%= gravatar_for sender_information(request.sender_id), size: 50 %>
        <h4><%= sender_information(request.sender_id).first_name %> <%= sender_information(request.sender_id).last_name %></h4>
      </div>
      <%= link_to accept_request_path(request.sender_id), method: :put, class:'darken-4 btn-flat follow-btn' do %>
        <i class="material-icons left">check</i>Accept
      <% end %>
      <%= link_to reject_request_path(request.sender_id), method: :delete, class:'darken-4 btn-flat follow-btn' do %>
        <i class="material-icons left">close</i>Reject
      <% end %>
    </div>
  <% end %>
</div>