config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/add_friend/:friend_id', to: 'friendships#create', as: :send_request
  put '/accept_friend/:sender_id', to: 'friendships#accept', as: :accept_request
  delete '/reject_friend/:sender_id', to: 'friendships#reject', as: :reject_request
  get '/received_requests', to: 'users#show', as: :received_requests
  get '/users', to: "users#index", as: :users
  get '/add_comment/:post_id', to: 'comments#new', as: :show_comment
  post '/add_comment/:post_id', to: 'comments#create', as: :create_comment
  get '/add_like/:post_id', to: 'likes#create', as: :like
  delete '/delete_like/:post_id', to: 'likes#destroy', as: :unlike
  resources :posts
  devise_for :users,
  :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' },
  :skip => [:registrations, :sessions]
  root to: "posts#index"
  
  devise_scope :user do
    get "/profile", to: "users/registrations#show"
    get "/signup", to: "users/registrations#new", as: :signup
    post "user/sign_up", to: "users/registrations#create", as: :user_registration
    post "/signin", to: "users/sessions#create", as: :signin
    get "/edit_user", to: "users/registrations#edit", as: :user_edit
    patch "/edit_user", to: "users/registrations#update" 
    delete "/signout", to: "users/sessions#destroy", as: :signout
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments
  validates :content, presence: true, length: { maximum: 255 }

  def self.find_user_posts(id)
    Post.where(user_id: id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authorize, only: [:index]

  def index
    @post = Post.new
    @posts = show_friends_posts
  end

  def show; end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save
      redirect_to root_path
    else
      @posts = Post.where(user_id: current_user.id)
      render :index
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:content, :user_id)
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container post-container">
  <div class="content-box">
    <%= render "shared/error_messages", resource: @post %>
    <%= render 'layouts/new_post'%>
  </div>
  <div class = "content-box">
    <% @posts.each do |post| %>
      <div class="post-card">
        <div class="user">
          <%= gravatar_for post.user, size: 50 %>
          <div class="name-date">
            <h4> <%= post.user.first_name.capitalize %> </h4>
            <p class="post-date"> <%= post.created_at.strftime("%B %d at %H:%M") %></p>
          </div>
        </div>
        <p> <%= post.content %> </p>
        <div class="card-buttons">
          <% if user_likes_post?(post.id) %>
            <%= link_to unlike_path(post), method: :delete, class:'darken-4 btn-flat' do %>
              <i class="material-icons left">thumb_down</i> Unlike
            <% end %>
          <% else %>
            <%= link_to like_path(post), class:'darken-4 btn-flat' do %>
              <i class="material-icons left">thumb_up</i> Like
            <% end %>
          <% end %>
          <%= link_to show_comment_path(post), class:'darken-4 btn-flat' do %>
            <i class="material-icons left">comment</i> comment
          <% end %>
        </div>
        <div class="number-likes-comments">
          <% if post.likes.any? %>
          <span> <%= "#{pluralize(post.likes.count, 'like')}" %></span>
          <% end %>
          <% if post.comments.any? %>
            <span class="post-comments right-align right"><%= link_to "#{pluralize(post.comments.count, 'comment')}", show_comment_path(post) %></span>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>