config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/add_friend/:friend_id', to: 'friendships#create', as: :send_request
  put '/accept_friend/:sender_id', to: 'friendships#accept', as: :accept_request
  delete '/reject_friend/:sender_id', to: 'friendships#reject', as: :reject_request
  get '/received_requests', to: 'users#show', as: :received_requests
  get '/users', to: "users#index", as: :users
  get '/add_comment/:post_id', to: 'comments#new', as: :show_comment
  post '/add_comment/:post_id', to: 'comments#create', as: :create_comment
  get '/add_like/:post_id', to: 'likes#create', as: :like
  delete '/delete_like/:post_id', to: 'likes#destroy', as: :unlike
  resources :posts
  devise_for :users,
  :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' },
  :skip => [:registrations, :sessions]
  root to: "posts#index"
  
  devise_scope :user do
    get "/profile", to: "users/registrations#show"
    get "/signup", to: "users/registrations#new", as: :signup
    post "user/sign_up", to: "users/registrations#create", as: :user_registration
    post "/signin", to: "users/sessions#create", as: :signin
    get "/edit_user", to: "users/registrations#edit", as: :user_edit
    patch "/edit_user", to: "users/registrations#update" 
    delete "/signout", to: "users/sessions#destroy", as: :signout
  end
end

app/views/layouts/_comment_form.html.erb
<%= form_for @comment, :url => create_comment_path(@post) do |f| %>
  <%= f.text_area :content, size: "60x20", class: "textarea", placeholder: "Write a comment.." %>
  <div class="actions">
    <%= f.submit "Create comment", class: "new-post-button" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo big-logo">Fakebook</a>
      <% if user_signed_in? %>
        <ul id="nav-mobile" class="right hide-on-med-and-down mid">
          <li><%= link_to "Home", root_path %></a></li>
          <li><%= link_to "Profile", profile_path %></a></li>
          <li><%= link_to "Find Friends", users_path %></a></li>
          <li>
            <%= link_to received_requests_path(), class:'darken-4 btn-flat follow-btn pending-btn', id: 'notification' do %>
              <i class="material-icons">group</i>
              <% if pending_requests.positive? %>
                <p class="float-p">
                  <%= pending_requests %>
                </p>
              <% end %>
            <% end %>
          </li>
          <li><%= link_to "Log out", signout_path, method: :delete %></a></li>
        </ul>
      <% else %>
        <ul>
          <%= render 'layouts/signin' %>
        </ul>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_new_post.html.erb
<%= form_for @post do |f| %>
  <%= f.text_area :content, size: "60x20", class: "textarea", placeholder: "What are you thinking, #{current_user.first_name.capitalize}?" %>
  <div class="actions">
    <%= f.submit "Create post", class: "new-post-button" %>
  </div>
<% end %>

app/views/layouts/_signin.html.erb
<%= form_for(:session, :url => signin_path(:session)) do |f| %>
    <%= f.email_field :email, autocomplete: "email", placeholder: "Email"%>

    <%= f.password_field :password, autocomplete: "current-password", placeholder: "Password"%>
    <div class="field check-box">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/icon?family=Material+Icons' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>